### PR TITLE
Create SwerveManualHeadingControl per chirag's req

### PR DESCRIPTION
**Pull request by ShahzebL**

### CODE REVIEW

**Comment by ShahzebL** [comment]
ooga booga

**Comment by CMEONE** [comment]
very interesting descriptions (also u do know u can make another commit to ur branch to rename a file and it gets added to the open pr right?)

**Review by CMEONE — DISMISSED** [review]
seems legit

**Review by SHAD0WV1RUS — APPROVED** [review]
Ooga booga

**Pull request closed without merging**
